name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: lloydbutay123
          outputs: dist/snake.svg

      # Step 3: Commit and Push Changes
      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/snake.svg
          git commit -m "Updated snake animation [skip ci]" || echo "No changes to commit"
          git push origin output
